version: '2'
services:
  db:
    container_name: mariadb
    build:
      context: ./docker/mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: parking_manager
    volumes: 
      - ./docker/data/db:/var/lib/mysql
  php-apache:
    container_name: php-apache
    build: 
        context: ./docker/web
    working_dir: /app
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - ./ParkingManager:/app
      - var:/app/var


volumes:
  var:

