version: '2'
services:
  db:
    container_name: mariadb
    build:
      context: ./docker/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: parking_manager
    volumes:
      - data:/var/lib/mysql
  node:
    container_name: node
    build:
      context: ./docker/nodejs
    volumes:
      - ./ParkingManager/assets:/app/assets
      - build:/app/public/build
  php-apache:
    container_name: php-apache
    build:
        context: ./docker/web
    working_dir: /app
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ./ParkingManager:/app
      - build:/app/public/build

volumes:
  build:
  data:
