index:
    path: /
    controller: App\Controller\DefaultController::index

webhook:
    path: /webhook
    controller: App\Controller\DefaultController::WebhookAction

dashboard_show:
    path: /dashboard
    controller: App\Controller\DashboardController::show

