index:
    path: /
    controller: App\Controller\DefaultController::index

webhook:
    path: /webhook
    controller: App\Controller\DefaultController::WebhookAction

dashboard_show:
    path: /dashboard
    controller: App\Controller\DashboardController::show

auslastung:
    path: /auslastung
    controller: App\Controller\AuswertungController::Auslastung

heatmap:
    path: /heatmap
    controller: App\Controller\AuswertungController::Heatmap
